---
label: product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: id
- name: name
  type: text
  config:
    required: false
  label: name
- name: price
  type: number
  label: price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: image
  type: text
  config:
    required: false
  label: image
- name: product_url
  type: text
  config:
    required: false
  label: product_url
- name: carat_weight
  type: number
  label: diamond_carat
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: diamond_color
  type: text
  config:
    required: false
  label: diamond_color
- name: diamond_cut
  type: text
  config:
    required: false
  label: diamond_cut
- name: diamond_clarity
  type: text
  config:
    required: false
  label: diamond_clarity
pages:
- content/products/RING1.md
- content/products/file.md
